[tool.black]
line-length = 100
# https://github.com/psf/black/issues/1473#issuecomment-740008873
exclude = '''
^/(
  (
    | advent_of_code/advent2020
    | crack-coding-interview
  )/
  | random.py
)
'''
