name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  python:

    runs-on: ubuntu-latest
    name: python

    steps:

    - uses: actions/checkout@v2

    - run: pip install -r requirements.txt

    - run: black --check .
  
    - run: pytest
